name: unit-test

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make env files
        run: |
          cp ${{github.workspace}}/.app_prop_sample ${{github.workspace}}/.app_prop_test
          echo "APP_EXEC_MODE=test" > ${{github.workspace}}/.env
          echo "PYTHONPATH=./src" >> ${{github.workspace}}/.env
          while read line;
          do
            echo $line >> $GITHUB_ENV
          done<${{github.workspace}}/.env
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          cache: 'poetry'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Add path for Poetry
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install Dependencies
        run: poetry install
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: poetry run task test_cov
          coverageLocations: ${{github.workspace}}/build/tests/coverage.xml:coverage.py
